INSERT INTO country (label, tag)
VALUES ('Royaume-Uni', 'ENG'),
       ('France', 'FRA'),
       ('Espagne', 'ESP'),
       ('Allemagne', 'DEU'),
       ('Italie', 'ITA'),
       ('Japon', 'JPN'),
       ('Chine', 'CHI'),
       ('Russie', 'RUS'),
       ('Arabie Saoudite', 'ARA'),
       ('Portugal', 'POR'),
       ('Pays-Bas', 'NLD'),
       ('Grèce', 'GRE'),
       ('Turquie', 'TUR'),
       ('Corée du Sud', 'KOR'),
       ('Vietnam', 'VIE'),
       ('Pologne', 'POL'),
       ('Suède', 'SWE'),
       ('Norvège', 'NOR'),
       ('Finlande', 'FIN'),
       ('Danemark', 'DAN'),
       ('Inde', 'HIN'),
       ('Bangladesh', 'BEN'),
       ('Thaïlande', 'THA'),
       ('Israël', 'HEB'),
       ('Hongrie', 'HUN');
