
INSERT INTO country (label_country, tag_country)
VALUES ('Anglais', 'ENG'),
       ('Français', 'FRA'),
       ('Espagnol', 'ESP'),
       ('Allemand', 'DEU'),
       ('Italien', 'ITA'),
       ('Japonais', 'JPN'),
       ('Chinois', 'CHI'),
       ('Russe', 'RUS'),
       ('Arabe', 'ARA'),
       ('Portugais', 'POR'),
       ('Néerlandais', 'NLD'),
       ('Grec', 'GRE'),
       ('Turc', 'TUR'),
       ('Coréen', 'KOR'),
       ('Vietnamien', 'VIE'),
       ('Polonais', 'POL'),
       ('Suédois', 'SWE'),
       ('Norvégien', 'NOR'),
       ('Finnois', 'FIN'),
       ('Danois', 'DAN'),
       ('Hindi', 'HIN'),
       ('Bengali', 'BEN'),
       ('Thai', 'THA'),
       ('Hébreu', 'HEB'),
       ('Hongrois', 'HUN');